---
title: "tidying_portion"
author: "Sol Bixby"
date: "10/29/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo =FALSE}
library(tidyverse)
library(readr)
```

```{r, echo =FALSE, warning=FALSE, message=FALSE}
ICPMS_imported <- read.csv("~/Chem 313/Chemistry_313_ICPMS_Lab/data/ICPMS_Data.csv", skip=1, na="N/A")

      sample_key <- read.csv("~/Chem 313/Chemistry_313_ICPMS_Lab/data/Sample_Key.csv", skip=0)
      
      
ICPMS_imported
sample_key

RSD_data<-ICPMS_imported %>%

select(Cr52 = CPS.RSD,
       Cr53 = CPS.RSD.1,
       As75 = CPS.RSD.2,
       Cd111 = CPS.RSD.3,
       Cd114 = CPS.RSD.4,
       Pb208 = CPS.RSD.5,
       Ge_RSD = CPS.RSD.7,
       Sample.Key)%>%
  pivot_longer(1:6,
               names_to = "metal",
               values_to="RSD")

View(RSD_data)

ICPMS_tidy<-ICPMS_imported %>%

select(Cr52 = CPS,
       Cr53 = CPS.1,
       As75 = CPS.2,
       Cd111 = CPS.3,
       Cd114 = CPS.4,
       Pb208 = CPS.5,
       Ge72 = CPS.7,
       Sample.Key)%>%
  pivot_longer(1:6,
               names_to = "metal",
               values_to="CPS")%>%
  mutate(RSD = RSD_data$RSD/RSD_data$Ge_RSD,
         CPS=CPS/Ge72)%>%
  select(-Ge72)

all(RSD_data$Sample.Key==ICPMS_tidy$Sample.Key, RSD_data$metal==ICPMS_tidy$metal)

ICPMS_merged<-merge(ICPMS_tidy, sample_key)

View(ICPMS_merged)

write.csv(ICPMS_merged, file = "~/Chem 313/Chemistry_313_ICPMS_Lab/data/ICPMS_merged.csv")
```
